### PR TITLE
fix: Prevent NX from loading .env files when running CLI scripts.

### LINKED ISSUE #475: Enviroment variables loaded from `.env` file during backend build.
### Describe the bug

I am trying to run build using `pnpm saas build` and on `build:backend` step I'm getting `Error: getaddrinfo ENOTFOUND localstack`. I believe that the reason of that is that `nx` is loading env files by default: https://nx.dev/recipes/tips-n-tricks/define-environment-variables and in local `.env` file I have a default value for `AWS_ENDPOINT_URL` with `localstack` value. 

As a temporary fix I was able to add a line `delete process.env.AWS_ENDPOINT_URL` at the beginning of `packages/backend/scripts/build.js` file. I'm not 100% if this fixes issue properly, but it allowed me to go further.

### Steps to reproduce

1. Ensure that in your `packages/backend/.env` file you have set `AWS_ENDPOINT_URL` value.
2. Run `pnpm saas build` 
3. At the step `nx run backend:build` you should receive error: `Error: getaddrinfo ENOTFOUND localstack`

### System Info

```shell
System:
    OS: macOS 12.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 922.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 15.6.1
  npmPackages:
    @apollo/client: ^3.8.8 => 3.8.8
    @apollo/rover: ^0.19.1 => 0.19.1
    @aws-sdk/client-cloudformation: ^3.462.0 => 3.462.0
    @aws-sdk/client-codebuild: ^3.462.0 => 3.462.0
    @aws-sdk/client-ecr: ^3.462.0 => 3.462.0
    @aws-sdk/client-ecs: ^3.462.0 => 3.462.0
    @aws-sdk/client-iam: ^3.462.0 => 3.462.0
    @aws-sdk/client-lambda: ^3.462.0 => 3.462.0
    @aws-sdk/client-s3: ^3.462.0 => 3.462.0
    @aws-sdk/client-ses: ^3.462.0 => 3.462.0
    @aws-sdk/client-sfn: ^3.462.0 => 3.462.0
    @aws-sdk/client-sts: ^3.462.0 => 3.462.0
    @babel/preset-react: ^7.23.3 => 7.23.3
    @graphql-codegen/cli: ^5.0.0 => 5.0.0
    @graphql-typed-document-node/core: ^3.2.0 => 3.2.0
    @iconify-icons/ion: ^1.2.10 => 1.2.10
    @iconify/react: ^4.1.1 => 4.1.1
    @nx/devkit: 17.1.3 => 17.1.3
    @nx/eslint: 17.1.3 => 17.1.3
    @nx/eslint-plugin: 17.1.3 => 17.1.3
    @nx/jest: 17.1.3 => 17.1.3
    @nx/js: 17.1.3 => 17.1.3
    @nx/node: 17.1.3 => 17.1.3
    @nx/plugin: 17.1.3 => 17.1.3
    @nx/react: 17.1.3 => 17.1.3
    @nx/web: 17.1.3 => 17.1.3
    @nx/webpack: 17.1.3 => 17.1.3
    @sb/cli: * => 2.4.2
    @sb/core: * => 2.4.2
    @sentry/react: ^7.84.0 => 7.84.0
    @storybook/addon-actions: ^7.6.1 => 7.6.1
    @storybook/react: ^7.6.1 => 7.6.1
    @supercharge/strings: ^2.0.0 => 2.0.0
    @svgr/webpack: ^8.1.0 => 8.1.0
    @tailwindcss/typography: ^0.5.10 => 0.5.10
    @testing-library/dom: ^9.3.3 => 9.3.3
    @testing-library/jest-dom: ^6.1.4 => 6.1.4
    @testing-library/react: 14.0.0 => 14.0.0
    @testing-library/react-hooks: ^8.0.1 => 8.0.1
    @testing-library/user-event: ^14.5.1 => 14.5.1
    @trivago/prettier-plugin-sort-imports: ^4.3.0 => 4.3.0
    @types/gtag.js: ^0.0.14 => 0.0.14
    @types/jest: ^29.5.10 => 29.5.10
    @types/node: ^18.18.14 => 18.18.14
    @types/ramda: ^0.28.25 => 0.28.25
    @types/react: 18.2.24 => 18.2.24
    @types/react-dom: 18.2.9 => 18.2.9
    @types/react-router: ^5.1.20 => 5.1.20
    @types/react-router-dom: 5.3.3 => 5.3.3
    @types/react-test-renderer: ^18.0.7 => 18.0.7
    @typescript-eslint/eslint-plugin: 6.13.1 => 6.13.1
    @typescript-eslint/parser: 6.13.1 => 6.13.1
    @typescript-eslint/scope-manager: 5.62.0 => 5.62.0
    @vitejs/plugin-react: ^4.2.0 => 4.2.0
    aws-cdk: ^2.111.0 => 2.111.0
    aws-cdk-lib: ^2.111.0 => 2.111.0
    babel-jest: 29.7.0 => 29.7.0
    constructs: ^10.3.0 => 10.3.0
    esbuild: 0.19.8 => 0.19.8
    eslint: ^8.54.0 => 8.54.0
    eslint-config-prettier: 9.0.0 => 9.0.0
    eslint-import-resolver-typescript: ^3.6.1 => 3.6.1
    eslint-plugin-formatjs: ^4.11.3 => 4.11.3
    eslint-plugin-import: 2.28.1 => 2.28.1
    eslint-plugin-jsx-a11y: ^6.8.0 => 6.8.0
    eslint-plugin-react: 7.33.2 => 7.33.2
    eslint-plugin-react-hooks: 4.6.0 => 4.6.0
    eslint-plugin-testing-library: ^6.2.0 => 6.2.0
    graphql: ^16.8.1 => 16.8.1
    husky: ^8.0.3 => 8.0.3
    jest: 29.7.0 => 29.7.0
    jest-environment-jsdom: 29.7.0 => 29.7.0
    jest-matcher-utils: ^29.7.0 => 29.7.0
    jest-watch-typeahead: ^2.2.2 => 2.2.2
    lint-staged: ^14.0.1 => 14.0.1
    nx: 17.1.3 => 17.1.3
    nx-cloud: 16.5.2 => 16.5.2
    plop: ^4.0.0 => 4.0.0
    prettier: ^3.1.0 => 3.1.0
    prettier-plugin-tailwindcss: ^0.5.7 => 0.5.7
    ramda: ^0.28.0 => 0.28.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-helmet-async: ^1.3.0 => 1.3.0
    react-hook-form: ^7.48.2 => 7.48.2
    react-intl: ^6.5.5 => 6.5.5
    react-loading-skeleton: ^3.3.1 => 3.3.1
    react-markdown: ^8.0.7 => 8.0.7
    react-router: ^6.16.0 => 6.16.0
    react-router-dom: 6.16.0 => 6.16.0
    regenerator-runtime: ^0.14.0 => 0.14.0
    styled-components: 6.0.8 => 6.0.8
    tailwindcss: ^3.3.5 => 3.3.5
    tailwindcss-animate: ^1.0.7 => 1.0.7
    ts-jest: 29.1.1 => 29.1.1
    ts-node: 10.9.1 => 10.9.1
    tsconfig-paths: ^4.2.0 => 4.2.0
    tslib: ^2.6.2 => 2.6.2
    typescript: 5.2.2 => 5.2.2
    vite: ^4.5.0 => 4.5.0
    vite-plugin-eslint: ^1.8.1 => 1.8.1
    vite-plugin-svgr: ^3.3.0 => 3.3.0
    vite-tsconfig-paths: ^4.2.1 => 4.2.1
```

### Logs

> nx run backend:build

>Error: getaddrinfo ENOTFOUND localstack
>Warning: run-commands command "node scripts/build.js" exited with non-zero status code

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

### PR DESCRIPTION
**Pull request by pziemkowski**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our guidelines

### What kind of change does this PR introduce?

Bug fix
Closes #475 

### What is the current behavior?

NX loads .env files from webapp and backend packages when running CLI commands. Some of variables are interfering with the execution of the script. They should only be loaded by Docker or Vite during runtime of apps, not scripts.

### What is the new behavior?

Patched `nx` package to prevent this behaviour with an ENV variable set within CLI.

### Does this PR introduce a breaking change?

Not a breaking change but if someone used .env files in a wrong way that could cause conflict.

### CODE REVIEW

File: packages/internal/cli/src/config/env.ts [hunk 1]
```diff
@@ -48,6 +48,10 @@ export async function loadVersionEnv() {
   return version;
 }
 
+export const loadNxEnv = () => {
```
Comment (mkleszcz) [inline packages/internal/cli/src/config/env.ts:51]: I don't like this name... It should be sth like `disableNxEnv` for example

**Review by mkleszcz — CHANGES_REQUESTED** [review]
Please have a look on my comment

File: packages/internal/cli/src/config/env.ts (hunk 1 above)
Comment (pziemkowski) [reply packages/internal/cli/src/config/env.ts:51]: Hmm, ok. I was rather thinking it's a good place to put other NX-related envs in the future if necessary

**Review by mkleszcz — APPROVED** [review]
